#include <pj/config_site_sample.h>

#define PJMEDIA_CONF_USE_SWITCH_BOARD 1
#define PJMEDIA_AUDIO_DEV_HAS_PORTAUDIO 0 // audio on computer running this
#define PJMEDIA_AUDIO_DEV_HAS_WMME 0 // windows stuff
#define PJMEDIA_CONF_SWITCH_BOARD_BUF_SIZE 2000
#define PJMEDIA_SND_DEFAULT_REC_LATENCY  20
#define PJMEDIA_SND_DEFAULT_PLAY_LATENCY 100
#define PJMEDIA_HAS_G711_CODEC 1
#define PJMEDIA_HAS_FFMPEG 0
#define PJMEDIA_HAS_L16_CODEC 0
#define PJMEDIA_HAS_G722_CODEC 0
#define PJMEDIA_HAS_GSM_CODEC 0
#define PJMEDIA_HAS_SPEEX_CODEC 0
#define PJMEDIA_HAS_ILBC_CODEC 0
#define PJMEDIA_HAS_PASSTHROUGH_CODECS 1
#define PJMEDIA_HAS_PASSTHROUGH_CODEC_PCMU 0
#define PJMEDIA_HAS_PASSTHROUGH_CODEC_PCMA 1
