name: Wireguard gateway

on:
  workflow_dispatch: {}
  push:
    paths:
      - gateway/gateway.conf

jobs:
  deploy-gateway-config:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh/
          umask 177
          echo "${{secrets.GATEWAY_SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          echo "${{secrets.GATEWAY_SSH_KNOWN_HOSTS}}" > ~/.ssh/known_hosts
      - name: Upload wireguard config
        run: rsync -av gateway/gateway.conf github@gateway.hirschfeld.tech:/etc/wireguard
      - name: Restart wireguard
        run: ssh github@gateway.hirschfeld.tech sudo /bin/systemctl restart wg-quick@gateway
